# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created: Tue May  2 10:08:25 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1463, 927)
        MainWindow.setWindowTitle("NemAcquire")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/nema_icon_transparent.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget_VerticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.centralwidget_VerticalLayout.setObjectName("centralwidget_VerticalLayout")
        self.TopButtonLayout = QtGui.QHBoxLayout()
        self.TopButtonLayout.setObjectName("TopButtonLayout")
        self.nema_logo = QtGui.QLabel(self.centralwidget)
        self.nema_logo.setText("")
        self.nema_logo.setPixmap(QtGui.QPixmap(":/icon/Side_txt_logo_rescaled.png"))
        self.nema_logo.setObjectName("nema_logo")
        self.TopButtonLayout.addWidget(self.nema_logo)
        spacerItem = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.TopButtonLayout.addItem(spacerItem)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0.8)
        self.connection_label = QtGui.QLabel(self.centralwidget)
        self.connection_label.setSizePolicy(sizePolicy)
        self.connection_label.setMinimumSize(QtCore.QSize(55, 0))
        self.connection_label.setObjectName("connection_label")
        self.TopButtonLayout.addWidget(self.connection_label)
        self.connection_status_label = QtGui.QLabel(self.centralwidget)
        self.connection_status_label.setText("")
        self.connection_status_label.setObjectName("connection_status_label")
        self.TopButtonLayout.addWidget(self.connection_status_label)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.TopButtonLayout.addItem(spacerItem1)
        self.VSelectionLayout = QtGui.QVBoxLayout()
        self.HFilterLayout = QtGui.QHBoxLayout()
        self.HExposureLayout = QtGui.QHBoxLayout()
        self.HFilterLayout.setAlignment(QtCore.Qt.AlignLeft)
        self.HExposureLayout.setAlignment(QtCore.Qt.AlignLeft)
        self.VSelectionLayout.addLayout(self.HFilterLayout)
        self.VSelectionLayout.addLayout(self.HExposureLayout)
        self.TopButtonLayout.addLayout(self.VSelectionLayout)
        self.filter_label = QtGui.QLabel(self.centralwidget)
        self.filter_label.setObjectName("filter_label")
        self.HFilterLayout.addWidget(self.filter_label)
        self.highpass_comboBox = QtGui.QComboBox(self.centralwidget)
        self.highpass_comboBox.setMinimumSize(QtCore.QSize(130, 0))
        self.highpass_comboBox.setObjectName("highpass_comboBox")
        self.highpass_comboBox.addItem("")
        self.highpass_comboBox.addItem("")
        self.HFilterLayout.addWidget(self.highpass_comboBox)
        self.notch_comboBox = QtGui.QComboBox(self.centralwidget)
        self.notch_comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.notch_comboBox.setObjectName("notch_comboBox")
        self.notch_comboBox.addItem("")
        self.notch_comboBox.addItem("")
        self.notch_comboBox.addItem("")
        self.HFilterLayout.addWidget(self.notch_comboBox)
        
        self.exposure_label = QtGui.QLabel(self.centralwidget,0,30)
        self.exposure_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.exposure_label.setObjectName("exposure_label")
        self.exposure_label.setMaximumHeight(30)
        self.exposure_slider = QtGui.QSlider(self.centralwidget)
        self.exposure_slider.setMinimumSize(QtCore.QSize(100, 0))
        self.exposure_slider.setMaximum(30)
        self.exposure_slider.setMinimum(1)
        self.exposure_slider.setOrientation(QtCore.Qt.Horizontal)
        self.exposure_slider.setObjectName("exposure_slider")
        
        self.gain_label = QtGui.QLabel(self.centralwidget,0,30)
        self.gain_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gain_label.setObjectName("gain_label")
        self.gain_label.setMaximumHeight(30)
        self.gain_slider = QtGui.QSlider(self.centralwidget)
        self.gain_slider.setMinimumSize(QtCore.QSize(100, 0))
        self.gain_slider.setMaximum(30)
        self.gain_slider.setMinimum(1)
        self.gain_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gain_slider.setObjectName("gain_slider")

        self.auto_exp_gain_checkBox = QtGui.QCheckBox()
        self.auto_exp_gain_checkBox.setText("Auto Exp./Gain")
        self.auto_exp_gain_checkBox.setObjectName("auto_exp_gain_checkBox")

        
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.TopButtonLayout.addItem(spacerItem2)
        self.pushButtonROI = QtGui.QPushButton(self.centralwidget)
        self.pushButtonROI.setMinimumSize(QtCore.QSize(35,35))
        self.pushButtonROI.setObjectName("pushButtonROI")
        #self.TopButtonLayout.addWidget(self.pushButtonROI)
        self.pushButtonImage = QtGui.QPushButton(self.centralwidget)
        self.pushButtonImage.setMinimumSize(QtCore.QSize(35, 35))
        camera_icon = QtGui.QIcon()
        camera_icon.addFile(":/icon/camera.png",mode=QtGui.QIcon.Normal)
        camera_icon.addFile(":/icon/camera_disabled.png",mode=QtGui.QIcon.Disabled)
        self.pushButtonImage.setIcon(camera_icon)
        self.pushButtonImage.setIconSize(QtCore.QSize(25,25))
        self.pushButtonImage.setObjectName("pushButtonImage")
        self.pushButtonCameraSettings = QtGui.QPushButton(self.centralwidget)
        self.pushButtonCameraSettings.setMinimumSize(QtCore.QSize(35,35))
        self.pushButtonCameraSettings.setObjectName("pushButtonCameraSettings")
        #self.TopButtonLayout.addWidget(self.pushButtonImage)
        self.pushButtonRecord = QtGui.QPushButton(self.centralwidget)
        self.pushButtonRecord.setMinimumSize(QtCore.QSize(164, 35))
        self.pushButtonRecord.setObjectName("pushButtonRecord")
        self.TopButtonLayout.addWidget(self.pushButtonRecord)
        self.pushButtonExpNotes = QtGui.QPushButton(self.centralwidget)
        self.pushButtonExpNotes.setMinimumSize(QtCore.QSize(164, 35))
        self.pushButtonExpNotes.setObjectName("pushButtonExpNotes")
        self.TopButtonLayout.addWidget(self.pushButtonExpNotes)
        self.centralwidget_VerticalLayout.addLayout(self.TopButtonLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.graphicsLayoutWidget = GraphicsLayoutWidget(self.centralwidget)
        self.graphicsLayoutWidget.setObjectName("graphicsLayoutWidget")
        self.horizontalLayout_3.addWidget(self.graphicsLayoutWidget)
        self.centralwidget_VerticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1463, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuSwitch_Mode = QtGui.QMenu(self.menubar)
        self.menuSwitch_Mode.setMinimumSize(QtCore.QSize(0, 0))
        self.menuSwitch_Mode.setBaseSize(QtCore.QSize(0, 10))
        self.menuSwitch_Mode.setObjectName("menuSwitch_Mode")
        self.menuExperiement_Notes_Fields = QtGui.QMenu(self.menuSwitch_Mode)
        self.menuExperiement_Notes_Fields.setObjectName("menuExperiement_Notes_Fields")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuConnection = QtGui.QMenu(self.menubar)
        self.menuConnection.setObjectName("menuConnection")
        self.menuMicroscope = QtGui.QMenu(self.menubar)
        self.menuMicroscope.setObjectName("menuMicroscope")
        self.menuCamera = QtGui.QMenu(self.menubar)
        self.menuCamera.setObjectName("menuCamera")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setToolTip("")
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuItemAbout = QtGui.QAction(MainWindow)
        self.menuItemAbout.setObjectName("menuItemAbout")
        self.menuItemHelp = QtGui.QAction(MainWindow)
        self.menuItemHelp.setObjectName("menuItemHelp")
        self.menuItemAmpGuide = QtGui.QAction(MainWindow)
        self.menuItemAmpGuide.setObjectName("menuItemAmpGuide")
        self.actionReview_Mode = QtGui.QAction(MainWindow)
        self.actionReview_Mode.setObjectName("actionReview_Mode")
        self.menuItemShowVpp = QtGui.QAction(MainWindow)
        self.menuItemShowVpp.setCheckable(True)
        self.menuItemShowVpp.setObjectName("menuItemShowVpp")
        self.menuItemShowFreq = QtGui.QAction(MainWindow)
        self.menuItemShowFreq.setCheckable(True)
        self.menuItemShowFreq.setObjectName("menuItemShowFreq")
        self.menuItemShowOffset = QtGui.QAction(MainWindow)
        self.menuItemShowOffset.setCheckable(True)
        self.menuItemShowOffset.setObjectName("menuItemShowOffset")
        self.menuItemRunNoiseTest = QtGui.QAction(MainWindow)
        self.menuItemRunNoiseTest.setCheckable(False)
        self.menuItemRunNoiseTest.setObjectName("menuItemRunNoiseTest")
        self.menuItemToggleDemoMode = QtGui.QAction(MainWindow)
        self.menuItemToggleDemoMode.setCheckable(True)
        self.menuItemToggleDemoMode.setObjectName("menuItemToggleDemoMode")
        self.menuConnectionInfo = QtGui.QAction(MainWindow)
        self.menuConnectionInfo.setCheckable(False)
        self.menuConnectionInfo.setObjectName("menuConnectionInfo")
        self.menuItemTestSignalOnAmp = QtGui.QAction(MainWindow)
        self.menuItemTestSignalOnAmp.setCheckable(True)
        self.menuItemTestSignalOnAmp.setObjectName("menuItemTestSignalOnAmp")
        self.menuItemPower = QtGui.QAction(MainWindow)
        self.menuItemPower.setCheckable(True)
        self.menuItemPower.setObjectName("menuItemPower")
        self.menuItemGrid = QtGui.QAction(MainWindow)
        self.menuItemGrid.setCheckable(True)
        self.menuItemGrid.setObjectName("menuItemGrid")
        self.actionHighpass_Filter = QtGui.QAction(MainWindow)
        self.actionHighpass_Filter.setCheckable(True)
        self.actionHighpass_Filter.setObjectName("actionHighpass_Filter")
        self.action50Hz = QtGui.QAction(MainWindow)
        self.action50Hz.setCheckable(True)
        self.action50Hz.setObjectName("action50Hz")
        self.action60Hz = QtGui.QAction(MainWindow)
        self.action60Hz.setCheckable(True)
        self.action60Hz.setObjectName("action60Hz")
        self.actionSelect_Recording_Directory = QtGui.QAction(MainWindow)
        self.actionSelect_Recording_Directory.setObjectName("actionSelect_Recording_Directory")
        self.actionShow_Recording_Folder = QtGui.QAction(MainWindow)
        self.actionShow_Recording_Folder.setObjectName("actionShow_Recording_Folder")
        self.actionShow_Camera_panel = QtGui.QAction(MainWindow)
        self.actionShow_Camera_panel.setObjectName("actionShow_Camera_panel")
        self.actionShow_EPG_panel = QtGui.QAction(MainWindow)
        self.actionShow_EPG_panel.setObjectName("actionShow_EPG_panel")
        self.actionEnable = QtGui.QAction(MainWindow)
        self.actionEnable.setCheckable(True)
        self.actionEnable.setEnabled(False)
        self.actionEnable.setObjectName("actionEnable")
        self.menuItemShowPowerline = QtGui.QAction(MainWindow)
        self.menuItemShowPowerline.setCheckable(True)
        self.menuItemShowPowerline.setObjectName("menuItemShowPowerline")
        self.menuItemSetPowerlineThreshold = QtGui.QAction(MainWindow)
        self.menuItemSetPowerlineThreshold.setObjectName("menuItemSetPowerlineThreshold")
        self.actionShow_Camera_dialog = QtGui.QAction(MainWindow)
        self.actionShow_Camera_dialog.setObjectName("actionShow_Camera_dialog")
        self.actionShow_Camera_info = QtGui.QAction(MainWindow)
        self.actionShow_Camera_info.setObjectName("actionShow_Camera_info")
        self.menuHelp.addAction(self.menuItemAbout)
        self.menuHelp.addAction(self.menuItemHelp)
        self.menuSwitch_Mode.addAction(self.menuExperiement_Notes_Fields.menuAction())
        self.menuSwitch_Mode.addAction(self.actionSelect_Recording_Directory)
        self.menuSwitch_Mode.addAction(self.actionShow_Recording_Folder)
        self.menuView.addAction(self.actionShow_Camera_panel)
        self.menuView.addAction(self.actionShow_EPG_panel)
        self.menuView.addAction(self.menuItemPower)
        self.menuView.addAction(self.menuItemShowFreq)
        self.menuView.addAction(self.menuItemShowVpp)
        self.menuView.addAction(self.menuItemShowOffset)
        self.menuView.addAction(self.menuItemGrid)
        self.menuView.addAction(self.menuItemShowPowerline)
        self.menuView.addAction(self.menuItemSetPowerlineThreshold)
        self.menuConnection.addAction(self.menuConnectionInfo)
        self.menuConnection.addAction(self.menuItemRunNoiseTest)
        self.menuConnection.addAction(self.menuItemToggleDemoMode)
        self.menuConnection.addAction(self.menuItemTestSignalOnAmp)
        self.menuMicroscope.addAction(self.actionEnable)
        self.menuCamera.addAction(self.actionShow_Camera_info)
        self.menuCamera.addAction(self.actionShow_Camera_dialog)
        self.menubar.addAction(self.menuSwitch_Mode.menuAction())
        self.menubar.addAction(self.menuMicroscope.menuAction())
        self.menubar.addAction(self.menuConnection.menuAction())
        self.menubar.addAction(self.menuCamera.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.connection_label.setText(QtGui.QApplication.translate("MainWindow", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_label.setText(QtGui.QApplication.translate("MainWindow", "Filters:", None, QtGui.QApplication.UnicodeUTF8))
        self.highpass_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.highpass_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "1Hz Highpass", None, QtGui.QApplication.UnicodeUTF8))
        self.notch_comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.notch_comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "60Hz Notch - US", None, QtGui.QApplication.UnicodeUTF8))
        self.notch_comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "50Hz Notch - EU", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonROI.setText(QtGui.QApplication.translate("MainWindow",
            "ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonImage.setText(QtGui.QApplication.translate("MainWindow",
            "", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCameraSettings.setText(QtGui.QApplication.translate("MainWindow",
            "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRecord.setText(QtGui.QApplication.translate("MainWindow", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonExpNotes.setText(QtGui.QApplication.translate("MainWindow", "Experiment Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSwitch_Mode.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExperiement_Notes_Fields.setTitle(QtGui.QApplication.translate("MainWindow", "Experiment Notes Fields", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConnection.setTitle(QtGui.QApplication.translate("MainWindow", "Amplifier", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMicroscope.setTitle(QtGui.QApplication.translate("MainWindow", "Microscope", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItemAbout.setText(QtGui.QApplication.translate("MainWindow", "About NemAcquire", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCamera.setTitle(QtGui.QApplication.translate("MainWindow",
            "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItemHelp.setText(QtGui.QApplication.translate("MainWindow", "NemAcquire User Guide", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItemAmpGuide.setText(QtGui.QApplication.translate("MainWindow", "Amplifier User Guide", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReview_Mode.setText(QtGui.QApplication.translate("MainWindow", "Review Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItemShowVpp.setText(QtGui.QApplication.translate("MainWindow", "Show Amplitude", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItemShowFreq.setText(QtGui.QApplication.translate("MainWindow", "Show EPG Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItemShowOffset.setText(QtGui.QApplication.translate("MainWindow", "Show Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItemRunNoiseTest.setText(QtGui.QApplication.translate("MainWindow", "Run Noise Test", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItemToggleDemoMode.setText(QtGui.QApplication.translate("MainWindow", "Offline Demo Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConnectionInfo.setText(QtGui.QApplication.translate("MainWindow", "Connection Information", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItemTestSignalOnAmp.setText(QtGui.QApplication.translate("MainWindow", "Enable Test Signal on Amplifier", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItemPower.setText(QtGui.QApplication.translate("MainWindow", "Show Frequency Distribution Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItemGrid.setText(QtGui.QApplication.translate("MainWindow", "Show Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHighpass_Filter.setText(QtGui.QApplication.translate("MainWindow", "1Hz Highpass Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.action50Hz.setText(QtGui.QApplication.translate("MainWindow", "50Hz - Standard EU", None, QtGui.QApplication.UnicodeUTF8))
        self.action60Hz.setText(QtGui.QApplication.translate("MainWindow", "60Hz - Standard US", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelect_Recording_Directory.setText(QtGui.QApplication.translate("MainWindow", "Select Recording Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Recording_Folder.setText(QtGui.QApplication.translate("MainWindow", "Show Recording Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Camera_panel.setText(QtGui.QApplication.translate("MainWindow", "Show Camera panel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_EPG_panel.setText(QtGui.QApplication.translate("MainWindow", "Show EPG panel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnable.setText(QtGui.QApplication.translate("MainWindow", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItemShowPowerline.setText(QtGui.QApplication.translate("MainWindow", "Show Powerline Noise", None, QtGui.QApplication.UnicodeUTF8))
        self.menuItemSetPowerlineThreshold.setText(QtGui.QApplication.translate("MainWindow",
            "Set Powerline Noise Threshold : ", None, QtGui.QApplication.UnicodeUTF8))

        self.actionShow_Camera_dialog.setText(QtGui.QApplication.translate("MainWindow","Camera Settings"\
        , None, QtGui.QApplication.UnicodeUTF8))

        self.actionShow_Camera_info.setText(QtGui.QApplication.translate("MainWindow","Connection Information"\
        , None, QtGui.QApplication.UnicodeUTF8))
from pyqtgraph import GraphicsLayoutWidget
import logo_rc
